thing1 = input("Enter name of any object: ")
quality = input("Enter quality of someone: ")
alive_sup = input("Enter the name of any living or superstetious spieces: ")
lev_noice = input("Level of noice : ")
noice = input("Enter any sound or character: ")
quality2 = input("Enter the quality of someone: ")
alive_sup2 = input("Enter the name of any living or superstetious spieces: ")
thing2 = input("Enter the name of any object: ")
verb = input("Enter any verb: ")
thing3 = input("Enter the name of any thing: ")
print(f"I went to the store to buy a {thing1}. I was standing in line behind a {quality} {alive_sup} when I heard a {lev_noice} {noice} behind me. I turned around and saw a {quality2} {alive_sup2} wearing a {thing2} hat. I was so surprised that I {verb} my {thing3}.")